version: '2'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    links:
      - db
